#!/usr/bin/env bash

# config="${XDG_CONFIG_HOME:-$HOME/.config}/mum-rofi/mum-rofi.toml"

trim() {
    local var="$*"
    # remove leading whitespace characters
    var="${var#"${var%%[![:space:]]*}"}"
    # remove trailing whitespace characters
    var="${var%"${var##*[![:space:]]}"}"
    printf '%s' "$var"
}

sort_members() {
  local buf
  while IFS= read -r line
  do
    case "$line" in
      "    -"*)
        buf="${buf}\n${line}"
      ;;
      *)
        echo "$buf" | sed '/^$/d' | sort
        buf=""
        echo "$line"
      ;;
    esac
  done
}

print_status() {
  # room="$(mumctl status | grep -Po 'Currently in \K(.*)(?= with)')"
  # server="$(mumctl status | grep -Po 'Connected to \K(.*)(?= as)')"
  user="$(mumctl status | grep -Po 'Connected to (.*) as \K(.*)')"
  muted="$(mumctl status | tail -n+4 | grep -Po "$user"' \K(M?)')"
  deaf="$(mumctl status | tail -n+4 | grep -Po "$user"' M?\K(D?)')"

  output="$(mumctl channel list | sort_members)"
  if [ -n "$muted" ]; then
    output="$(echo -e "$output\n## unmute")"
  else
    output="$(echo -e "$output\n## mute")"
  fi

  if [ -n "$deaf" ]; then
    output="$(echo -e "$output\n## undeafen")"
  else
    output="$(echo -e "$output\n## deafen")"
  fi

  output="$(echo -e "$output\n## disconnect")"


  lines="$(echo "$output" | wc -l)"
  printf "\0theme\x1flistview {lines: %s;}\n" "$lines"
  echo "$output" #| sed -r 's/^( )*- .*/&\x00nonselectable\x1finfo\x1fuser/'
}

connection_menu() {
  case "$sel" in
    "")
      if [ "$ROFI_RETV" -eq 0 ]; then
        mumctl server list | grep -Po '(.*)(?=  [[0-9]+/[0-9]+])'
      fi
      exit 0
      ;;
    "##"*)
      action="$(echo "$sel" | sed -r 's/^## //g')"
      (mumctl "$action" && notify-send "mumble: $action success") || notify-send "mumble: $action failure"
      ;;
    *)
      mumctl connect "$sel" >/dev/null
      sleep 0.1
      print_status
      ;;
  esac
}

server_menu() {
  case "$sel" in
    "")
      if [ "$ROFI_RETV" -ne 0 ]; then
        exit 0
      fi
      ;;
    "##"*)
      action="$(echo "$sel" | sed -r 's/^## //g')"
      (mumctl "$action" && notify-send "mumble: $action success") || notify-send "mumble: $action failure"
      ;;
    *)
      (mumctl channel connect "$(trim "$sel")" &>/dev/null && notify-send "mumble: Switched to $sel") || notify-send "mumble: Error switching to $sel"
      ;;
  esac
  if [ "$ROFI_RETV" -ne 0 ]; then
    sleep 0.1
  fi
  print_status
}



## MAIN
if [ -z "${ROFI_RETV+x}" ]; then
  exec rofi -show mum -modes "mum:$0"
fi
sel="$*"

state="$(mumctl status)"
case "$state" in
  "error: Not connected to a server")
    connection_menu
  ;;
  "error: Unable to connect to mumd")
    echo "mumd not running"
  ;;
  "Connected"*)
    server_menu
  ;;
  *)
    echo "Unknown error"
    echo "$state"
  ;;
esac
